apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ritu_app
  namespace: default
spec:
  interval: 15m
  path: "./fluxcd/repositories/Ritu_app/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ritu_app
