apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: ritu-app-2
  labels:
    app: ritu-app-2
spec:
  type: ClusterIP
  selector:
    app: ritu-app-2
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
